### ISSUE TITLE
Spice of Life: Carrot Edition doesn't work with lunchboxes

### ISSUE THREAD

**Issue by tarinoita** [tarinoita/Spice-of-Life-Sweet-Potato#11]
I'm playing with both Carrot and Sweet Potato, and Carrot doesn't count any foods eaten from the lunchbox. It does try to count the lunchbox itself, though.

I'll see what I can do to add compatibility, probably by end of September.

**Comment by AngleWyrm10** [comment]
The separate mod [Lunchbox ](https://github.com/LegoMaster3650/Lunchbox) just released an alpha version for 1.18.2 that does count the foods as Spice of Life variety.

**Comment by tarinoita** [comment]
Fixed in 2.1.0
