### ISSUE TITLE
Incompatibility with First Aid for 1.19.2

### ISSUE THREAD

**Issue by GoldenPot8o** [tarinoita/Spice-of-Life-Sweet-Potato#13]
**Description**
There appears to be an incompatibility between this version of SoL and First Aid in the most recent 1.19.2 update. It causes player data to not be written properly when saving and exiting a world, resulting in a crash.
This was a known and solved incompatibility between SoL (Carrot Edition) and First Aid in earlier versions of Minecraft [https://github.com/ichttt/FirstAid/issues/115](url)

**Crashlog**
[crash-2022-10-14_18.56.38-server.txt](https://github.com/tarinoita/Spice-of-Life-Sweet-Potato/files/9790971/crash-2022-10-14_18.56.38-server.txt)

**To Reproduce**
Enter any Minecraft world with both SoL and First Aid downloaded, then attempt to save and quit to title.

**Mod and Forge Version Info**
solsweetpotato-1.19.2-2.0.0.jar
firstaid-1.12.0.jar
Forge version 43.1.32 and above

**Comment by tarinoita** [comment]
See my previous notes in #12 

AFAICT this is not the same issue as before, but a new issue potentially related to Forge's changes to Capabilities. We still have the [old compat](https://github.com/tarinoita/Spice-of-Life-Sweet-Potato/blob/d8ae93df939e60fbd43f6fe80afe9116168ece1c/src/main/java/com/tarinoita/solsweetpotato/tracking/benefits/AttributeBenefit.java#L67) for the health adjustment built in. Raise it to the First Aid folks--if they say there's something I should do, you can reopen a ticket about that.
