### ISSUE TITLE
Lunch bag disappears during play

### ISSUE THREAD

**Issue by AngleWyrm10** [tarinoita/Spice-of-Life-Sweet-Potato#2]
**Description**
The lunch bag vanishes from player hotbar during game play

**To Reproduce**
What I did: craft lunch bag, load with food items (some modded), place on hotbar, go adventuring.
This has occurred three times over the past two days.

v1.18.2-1.0.3, on Forge 40.1.73

If this were supposed to be a feature:
- There would be an easily recognizable durability indicator
- The food would drop when the bag ran out of durability
- Optionally the player would be notified of the incident

So it's a bug not a feature.

**Comment by tarinoita** [comment]
Yeah lunchbox durability isn't a thing. This hasn't happened to me so far, though. Does it happen when you're playing with ONLY this mod? If so, can you please attach a log from a game session where it happened? I have no clue what could cause that, so I need something more to work from.

**Comment by jgaines** [comment]
I had the same thing happen, but I think it was Alex's Mobs seagulls stealing my lunchbox (raccoons beg when I'm holding it, so it looks like food to them too).  I turned off seagull stealing and tested it out.  Been running around for a few in-game days now and lunchbox still there.
