### ISSUE TITLE
[1.19.2 / Tweak] Tooltip order could be tweaked to be more compatable with other mods.

### ISSUE THREAD

**Issue by murao-kun** [tarinoita/Spice-of-Life-Sweet-Potato#4]
**Description**
With some mods tooltip appearing higher than other modded tooltips. (Serene Seasons for example here)
You can change ItemTooltipEvent priority to be one lower than current value.
![image](https://user-images.githubusercontent.com/110398598/188596131-3c514986-728d-413c-824d-ccff37fb8f6e.png)

**To Reproduce**
Install both mods together and eat carrot for example.

**Mod version and Forge version**
Minecraft 1.19.2

**Comment by tarinoita** [comment]
This seems like personal preference, not going to change unless there's a compelling reason to.

**Comment by murao-kun** [comment]
It will stay the same, just be a little lower if other mods conflicting with it.
