### ISSUE TITLE
[1.19.2 / BUG] Conflict with Always Eat mod.

### ISSUE THREAD

**Issue by murao-kun** [tarinoita/Spice-of-Life-Sweet-Potato#5]
**Description**
I can't open lunchbox item. Any of them.

**Log files**
[debug.log](https://github.com/tarinoita/Spice-of-Life-Sweet-Potato/files/9495368/debug.log)
[latest.log](https://github.com/tarinoita/Spice-of-Life-Sweet-Potato/files/9495371/latest.log)

**To Reproduce**
Try to open any type of lunchbox.

**Mod version and Forge version**
Minecraft 1.19.2

**Comment by tarinoita** [comment]
Are you shift + right-clicking? (needs to be both!) This is working for me.

**Comment by murao-kun** [comment]
Just tested shift + right-clicking is making me just easting it instead same as only right click.

**Comment by tarinoita** [comment]
How are you eating it if you couldn't put anything in? Right-click (the usual "eating" button) doesn't do anything if the bag is empty.

Are you playing with default keybindings, or something customized? Do you have other mods that could be affecting this, or does it happen even if this is the only mod installed?

**Comment by murao-kun** [comment]
1) When the bag is empty, I can eat it, but the item will stay still.
2) I have default keybindings.
3) I have both potato and carrot editions.
The last thing could affect it.

**Comment by tarinoita** [comment]
Just tried with carrot edition (1.19.2-1.13.0) and it's not repro-ing. Can you try with only this mod installed and see if it still happens?

**Comment by tarinoita** [comment]
If it still happens:
Upload the debug log from that session

If it doesn't:
Figure out which mod(s) are causing the issue and let me know, I'll see what I can do for compat

Thanks!

**Comment by murao-kun** [comment]
Sure, will test and be back with results!

**Comment by murao-kun** [comment]
I found mod that causing the issue.
https://www.curseforge.com/minecraft/mc-mods/alwayseat

**Comment by murao-kun** [comment]
Found the they how to fix that without any code changes. Always Eat have server configuration file that have blacklist option, the issue is fixing by placing lunchbox id into that blacklist.
