### ISSUE TITLE
[1.19.2 / Tweak] You can copy vanilla bundle behavior to lunchbox.

### ISSUE THREAD

**Issue by murao-kun** [tarinoita/Spice-of-Life-Sweet-Potato#6]
**Description**
I suggest to left only one type of lunchbox and make it work like vanilla bundle, have blue bar that showing you how filled is that, have 64 items restriction to mutch that it is tacking one slot. Unstackable food could just take all the space as vanilla behavior too.
Have same tooltip UI.
![image](https://user-images.githubusercontent.com/110398598/188602031-5ee3584e-da92-4142-95a7-a9e166fe23d7.png)

**Mod version and Forge version**
Minecraft 1.19.2

**Comment by tarinoita** [comment]
No thanks. You can make your own version that works like that if you like.
