### ISSUE TITLE
incompatible with Always Eat

### ISSUE THREAD

**Issue by zeRan404** [tarinoita/Spice-of-Life-Sweet-Potato#9]
*I use google translate,sorry

When this mod installed with [Always Eat](https://www.curseforge.com/minecraft/mc-mods/alwayseat),shift click can't open lunch box

mod version：
solsweetpotato-1.18.2-1.0.3
AlwaysEat-5.1

**Comment by murao-kun** [comment]
Check out your world folder, find server configs and go to always eat config, there is blacklist to add lunchboxes.

**Comment by tarinoita** [comment]
Thanks Murao :)
